name: Auto Update Economic Calendar

on:
  schedule:
    - cron: '0 6 * * 0'  # Every Sunday at 6am UTC
  workflow_dispatch:  # Manual trigger option

jobs:
  scrape-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests beautifulsoup4 pandas

      - name: Run scraper
        run: python nci_news_scraper.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add calendar.csv
          git commit -m "Auto-update: Weekly economic calendar" || echo "No changes to commit"
          git push
